Dockerfile
amida-tech/saraswati-dashboard pull request #6
Opened 2021-06-17 18:30 UTC by hmayenve

**Description**

* Adding a Dockerfile to project

**Testing**
* Build up image ` docker build -t swati-demo-image:latest .`
* Run container `docker run -p 3000:3000 swati-demo-image:latest`
* Go to `http://localhost:3000/`

2021-06-29 12:59 UTC, jmfadeley requested changes
Fix the security issue and this is good.

2021-06-29 12:59 UTC, jmfadeley commented on Dockerfile
> +
This works, but you'll want to change the user for the Docker image for security reasons. I think most of our other repos do something like this.

2021-06-29 14:32 UTC, jmfadeley approved these changes

2021-06-30 20:07 UTC, eawest2 approved these changes
Works for me.

2021-06-30 20:07 UTC, merged